services:
  main:
    build:
      context: ./Bigabortion
      dockerfile: ./Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./Bigabortion:/app
      

  ghi:
    image: node:lts-bullseye
    command: /abortion2 run.sh
    working_dir: /app
    volumes:
      - ./abortion2:/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_API_HOST: ${REACT_APP_API_HOST}

      # REACT_APP_API_HOST: ${REACT_APP_API_HOST}
  # db:
  #   image: postgres:14.5-bullseye
  #   environment:
  #     POSTGRES_PASSWORD: secret
  #     POSTGRES_USER: example_user
  #     POSTGRES_DB: example
  #   ports:
  #     - "15432:5432"
  #   volumes:
  #     - checkit-data:/var/lib/postgresql/data
