FROM python:3.10-bullseye
ENV PYTHONUNBUFFERED 1
WORKDIR /app
# ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
# RUN chmod +x /wait
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN pip install requests
RUN pip install django channels
RUN pip install django-cors-headers

# Bundle app source
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]